### ISSUE TITLE
Dependence on input o

### ISSUE THREAD

**Issue by owenduffy** [openangletool/openangletool#1]
What a brilliant tool, thanks.

In my current use, I am only interested in calculating hr, and discovered that it is not dependent on hc.

I discovered that if I leave hc blank, it simplifies the result (omits hn) which is good.

![Screenshot-241023053032](https://github.com/user-attachments/assets/7ee8f644-0d41-414d-9810-5c680a0e51d7)

I expected it would not depend on o, but if I leave o blank, I get NaN for hc. If hc is independent of o, it would be nice if o could be left blank to show the simplified form that makes it clearer that o does not play in the hr value.

Owen

**Comment by schwebke** [comment]
Hi Owen,
thanks for the suggestion. The internal calculation solves for an angle that actually depends on _o_, even if the _hr_ part of the result does not.
I made the input more tolerant, so an empty input is treated as zero. In the case you highlighted, you now can leave both _o_ and _hc_ empty.

**Comment by owenduffy** [comment]
Thanks, that works after I force a reload of the page contents.
